version: "3.8"

services:
#    mysql:
#      image: mysql:8.0
#      container_name: testdb
#      ports:
#        - "${DATABASE_PORT}:3306"
#      environment:
#        MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
#        MYSQL_DATABASE: ${DATABASE_NAME}
#        TZ: Asia/Seoul
#      volumes:
#        - mysql-volume:/var/lib/testdb

  redis:
    image: redis:alpine
    container_name: redis_dev
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-volume:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_dev
    ports:
      - "${RABBITMQ_NODE_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq


volumes:
  redis-volume:
  rabbitmq-volume:
#  mysql-volume:
